Models/ErrorViewModel.cs
using System;

namespace CommunityWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CommunityWeb.Controllers
{
    public class CandidateController : Controller
    {
        public IActionResult InsertCandidate()
        {
            return View();
        }

        public IActionResult ShowCandidate()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CommunityWeb.Models;

namespace CommunityWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Member()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CommunityWeb.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CommunityWeb.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Profile()
        {
            return View();
        }
    }
}

Views/Candidate/ShowCandidate.cshtml
<div ng-controller="InsertCandidateController">
    <div class="container" ng-init="init()">
        <h3>ข้อมูล Candidate</h3>
        <div class="form-group">
            <label>Email address</label>
            <input type="text" class="form-control" ng-model="registerForm.email" id="" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="">Fullname</label>
            <input type="text" class="form-control" ng-model="registerForm.fullname" placeholder="Fullname">
        </div>
        <div class="form-group">
            <label for="">Experience</label>
            <input type="text" class="form-control" ng-model="registerForm.experience" placeholder="Experience">
        </div>
        <div class="form-group">
            <label for="">Age</label>
            <input type="text" class="form-control" ng-model="registerForm.age" placeholder="Age">
        </div>
        <div class="form-group">
            <label>Computer Language</label>
            <select class="form-control" ng-model="registerForm.computer_lang" id="">
                <option value="" disabled selected hidden>กรุณาเลือก</option>
                <option ng-repeat="sk in com_lang" value="{{sk.computer_lang_name}}">{{sk.computer_lang_name}}</option>
            </select>
        </div>
        <button class="btn btn-default" ng-click="sendData(registerForm)">ส่งข้อมูล</button>
    </div>
</div>

@section Scripts {
    <script src="~/js/InsertCandidateController.js"></script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container-fluid">
    <div class="header1">
        <div class="row justify-content-md-center">
            <div class="col-xs-1 font">
                <img src="~/images/logo/rocket.png" class="logo-rocket">
            </div>
            <div class="col-xs-3 font1">
                <img src="~/images/logo/Logo_G-ABLE.png" class="logo1">
            </div>
            <div class="col-xs-3 font2">
                COMMUNITY
            </div>
        </div>
        <div class="row font3 justify-content-md-center">
            CONNECT WITH COMMUNITY MEMBERS TO LEARN, GET INSPIRED, AND BLAZE TRAILS TOGETHER
        </div>
    </div>
</div>

<suction>
    <div class="container top1">
        <div class="row">
            <div class="col-md-8">
                <div class="jumbotron1">
                    <div class="row ">
                        <div class="col-md-6 border-right">
                            <!-- ANSWER -->
                            <p class="lead top2">
                                <img src="~/images/icon/ownership2.png" class="icon-size">
                                Answer
                            </p>
                            <hr class="my-4">
                            <p class="font-detail">
                                Ask questions, get tips, and share knowledge with the rest of the Trailblazer Community.
                            </p>
                            <div class="row">
                                <div class="col-md-3 m-bottom">
                                    <img src="~/images/profile/p1.jpg" class="img-size-profile2">
                                </div>
                                <div class="col-md-9">
                                    <p class="font-comment">
                                        formula to add completed date fields with controlling checkbox factor
                                    </p>
                                    <div class="row">
                                        <div class="col-md-4 time">
                                            20 hours
                                        </div>
                                        <div class="col-md-4 comment">
                                            5 comments
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <img src="~/images/profile/p11.jpg" class="img-size-profile2">
                                </div>
                                <div class="col-md-9">
                                    <p class="font-correct">
                                        <img src="~/images/logo/tick.png" class="correct">
                                        See the Best Answer
                                    </p>
                                </div>
                                <div class="col-md-12">
                                    <hr class="my-4">
                                    <center>
                                        <button class="btn1">EXPLORE ANSWERS</button>
                                    </center>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <p class="lead top2">
                                <!-- ANSWER LEADERS-->
                                <img src="~/images/icon/excellence3.png" class="icon-size">
                                Answer Leaders
                            </p>
                            <hr class="my-4">
                            <p class="font-detail">
                                Meet the Trailblazers who go above and beyond to help community members succeed with Salesforce.
                            </p>
                            <center>
                                <img src="~/images/profile/p1.jpg" class="img-size-profile">
                                <img src="~/images/profile/p2.jpg" class="img-size-profile">
                                <img src="~/images/profile/p3.jpg" class="img-size-profile">
                                <img src="~/images/profile/p4.jpg" class="img-size-profile">
                                <img src="~/images/profile/p5.jpg" class="img-size-profile">
                                <img src="~/images/profile/p6.jpg" class="img-size-profile">
                                <img src="~/images/profile/p7.jpg" class="img-size-profile">
                                <img src="~/images/profile/p8.jpg" class="img-size-profile">
                                <img src="~/images/profile/p9.jpg" class="img-size-profile">
                                <img src="~/images/profile/p10.jpg" class="img-size-profile">
                                <img src="~/images/profile/p11.jpg" class="img-size-profile">
                                <img src="~/images/profile/p12.jpg" class="img-size-profile">
                            </center>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="container1">
                    <img src="~/images/icon/ad1.jpg" class="ad">
                    <button asp-controller="Home" asp-action="Index" class="btn2">Get Start</button>
                </div>
                <a href="#">
                    <div class="container1 top6">
                        <img ng-click="customerfocus()" src="~/images/icon/ad2.jpg" class="ad">
                    </div>
                </a>
            </div>

            <!--Colllaborate-->
            <div class="col-md-8">
                <div class="jumbotron1">
                    <p class="lead top3">
                        <img src="~/images/icon/teamwork2.png" class="icon-size">
                        Collaborate
                    </p>
                    <hr class="my-4">
                    <p class="font-detail2">
                        There's always a conversation happening in the Trailblazer Community. Jump in to add your voice and meet fellow trailblazers.
                    </p>

                    <!--comment-->
                    <div class="row">
                        <div class="col-md-2 m-bottom">
                            <img src="~/images/profile/p5.jpg" class="img-size-profile2">
                        </div>
                        <div class="col-md-10 left">
                            <p class="font-comment2">
                                * Release Readiness Trailblazers * - อริสรา ประภากาญจนกุล
                            </p>
                            <p class="detail-com">
                                Hi All, Here's an idea about Trailhead. Please Upvote if it helps you achieve your day-to-day certification maintenance goals. https://success.salesforce.com/ideaView?id=0873A0000003aMjQAI
                                <a href="#">...More</a>
                            </p>
                            <p class="time top5">
                                10 hours ago &middot; 8  omments &middot; 0 likes
                            </p>
                        </div>

                        <div class="col-md-2 m-bottom">
                            <img src="~/images/profile/p1.jpg" class="img-size-profile2">
                        </div>
                        <div class="col-md-10 left">
                            <p class="font-comment2">
                                * Sales Cloud - Getting Started * - สุภาวดี ทองคำ
                            </p>
                            <p class="detail-com">
                                Do you have questions about Sales Cloud? Don't know where to turn? Did you miss Tuesday's Office hour????  Join our weekly (Thursday) Sales Cloud Open Office Hours! Get your questions answered live by a Sales Cloud expert. ** Please create a case at help.salesforce.com if something is broken
                                <a href="#">...More</a>
                            </p>
                            <p class="time top5">
                                8 hours ago &middot; 2  omments &middot; 0 likes
                            </p>
                        </div>

                        <div class="col-md-2 m-bottom">
                            <img src="~/images/profile/p6.jpg" class="img-size-profile2">
                        </div>
                        <div class="col-md-10 left">
                            <p class="font-comment2">
                                Trailhead - ชัชวาล สิทธิทุม
                            </p>
                            <p class="detail-com">
                                Hi Experts,  I need help in Linking Webassesor account to Trailhead. I followed the instructions from the email i received but i didnt see any option to link my webassesor account to my trailhead account. I already followed the step in http://certification.force.com/pkb/articles/Public_KB/Link-Your
                                <a href="#">...More</a>
                            </p>
                            <p class="time top5">
                                6 hours ago &middot; 2  omments &middot; 0 likes
                            </p>
                        </div>
                        <div class="col-md-12">
                            <hr class="my-4">
                            <center>
                                <button class="btn1">JOIN THE CONVERSATION</button>
                            </center>
                        </div>
                    </div>
                    <!--end comment-->
                </div>
            </div>

            <div class="col-md-4 top7">
                <div class="jumbotron1">
                    <p class="lead top2">
                        <img src="~/images/logo/logo.png" class="logo2">
                        Featured G-ABLE
                    </p>
                    <hr class="my-4">
                    <p class="font-detail3">
                        Meet a community member who's blazing a trail with Salesforce.
                    </p>
                    <div class="row top6">
                        <div class="col-md-3 m-bottom">
                            <img src="~/images/profile/p9.jpg" class="img-size-profile2">
                        </div>
                        <div class="col-md-9 left">
                            <p class="font-name">
                                อัญชลี รักษาศิริ
                            </p>
                            <p class="font-content">
                                Application Architect - Salesforce...
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 b-margin">
                            <p class="font-detail4">
                                Multi-certified Senior Salesforce Consultant at 4C, a European Salesforce Platinum Partner (www.weare4c.com). Working with Salesforce since 2009 this #Hacker_Astro is an enthousiastic problem solver with a “Can Do” mentality and has a passion for Sales, Marketing, CPQ & Billing. Belgium User Group L...
                            </p>
                            <hr class="my-4">
                            <p>
                                <img src="~/images/icon/medal.png" class="icon2">
                                <span class="font-badges">Badges</span>
                                <span class="font-badges2">226</span>
                                <span class="font-badges">Point</span>
                                <span class="font-badges3">132,800</span>
                            </p>
                            <hr class="my-4">
                            <p>
                                <img src="~/images/icon/diploma.png" class="icon2">
                                <span class="font-badges">Certifications</span>
                                <span class="font-badges2">10</span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</suction>

Views/Home/Member.cshtml
@{
    ViewData["Title"] = "Member";
}

<h2>Member</h2>
<div class="twPc-div">
    <a class="twPc-bg twPc-block"></a>
    <div>
        <a  class="twPc-avatarLink">
            <img alt="Mert S. Kaplan" src="https://mertskaplan.com/wp-content/plugins/msk-twprofilecard/img/mertskaplan.jpg" class="twPc-avatarImg">
        </a>
        <div class="twPc-divUser">
            <div class="twPc-divName">
                <a >Mert S. Kaplan</a>
            </div>
            <span>
                <a><span>mertskaplan</span></a>
            </span>
        </div>
        <div class="twPc-divStats">
            <ul class="twPc-Arrange">
                <li class="twPc-ArrangeSizeFit">
                    <a  title="9.840 Tweet">
                        <span class="twPc-StatLabel twPc-block">Budges</span>
                        <span class="twPc-StatValue">9</span>
                    </a>
                </li>
                <li class="twPc-ArrangeSizeFit">
                    <a  title="885 Following">
                        <span class="twPc-StatLabel twPc-block">Point</span>
                        <span class="twPc-StatValue">885</span>
                    </a>
                </li>
                <li class="twPc-ArrangeSizeFit">
                    <a  title="1.810 Followers">
                        <span class="twPc-StatLabel twPc-block">Certificate</span>
                        <span class="twPc-StatValue">4</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

Views/Login/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

@*<div class="container-fluid">
        <div class="header-login">
            <div class="row justify-content-md-center">
                <div class="col-sm-10 font-login">
                    Login
                </div>
            </div>
        </div>
    </div>*@

<div ng-controller="LoginController" class="margin-head">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-sm-6 border-right">
                <img src="~/images/cover/banner-login.jpg" class="img-login" />
            </div>

            <div class="col-sm-6  margin-head">
                <div class="col-sm-10 font-login ">
                    Login
                </div>
                <div class="col-sm-10">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-user"></i></div>
                            </div>
                            <input type="text" class="form-control" ng-model="loginForm.username" id="" placeholder="username">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-unlock"></i></div>
                            </div>
                            <input type="password" class="form-control" ng-model="loginForm.password" placeholder="password">
                        </div>
                    </div>

                    <button class="btn btn-default width-button" ng-click="login(loginForm)">Login</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="margin-bottom">

</div>
@section Scripts {
    <script src="~/js/LoginController.js"></script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="myapp" ng-controller="MainController">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CommunityWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/style.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/login-style.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/profile-style.css" />
    <link rel="stylesheet" href="~/lib/font-awesome-4.7.0/css/font-awesome.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <environment include="Development">

    </environment>
    <environment exclude="Development">
        <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Kanit:200,300,400" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Yantramanav:100,300,400,500,700" rel="stylesheet">
    </environment>
</head>
<body>
    <div ng-init="init()">
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-nav">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <span class="navbar-brand mb-0 h1">
                    <img src="~/images/logo/Logo_G-ABLE.png" class="logo">
                    <span class="font">COMMUNITY</span>
                </span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse topnav-right" id="navbarText">
                <ul class="navbar-nav mr-auto" id="menu">
                    <li class="nav-item active" id="nav" value="1">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item" id="nav" value="2">
                        <a class="nav-link" href="answer.html">Answers</a>
                    </li>
                    <li class="nav-item" id="nav" value="3">
                        <a class="nav-link" href="Help.html">Help</a>
                    </li>
                    <li class="nav-item dropdown" id="nav" value="4">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Core Values
                        </a>
                        <div class="dropdown-menu" aria-labelledby="4">
                            <a class="nav-link" ng-click="customerfocus()" href="#">Customer Focus</a>
                            <a class="nav-link" href="#">Growth</a>
                            <a class="nav-link" href="#">Excellence</a>
                            <a class="nav-link" href="#">Teamwork</a>
                            <a class="nav-link" href="#">Ownership</a>
                        </div>
                    </li>
                    <li class="nav-item" id="nav" value="5">
                        <a ng-show="checked !== 'app'" class="nav-link" asp-controller="Login" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item dropdown" ng-show="checked === 'app'">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="" role="button" data-toggle="dropdown">
                            {{profile.fullname}}
                        </a>
                        <div class="dropdown-menu">
                            <a ng-show="checked === 'app'" class="nav-link" asp-controller="Profile" asp-action="Profile">Profile</a>
                            <a ng-show="checked === 'app'" class="nav-link" asp-controller="" asp-action="">My Groups</a>
                            <a ng-show="checked === 'app'" class="nav-link" ng-click="logout()" asp-controller="" asp-action="">Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div>
        @RenderBody()
        <div class="footer">
            <p class="top7">&#9400; G-ABLE Community</p>
        </div>
    </div>

    <environment include="Development">

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>

    </environment>
    <script src="~/js/site.js"></script>
    <script src="~/js/site.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/angular-1.7.2/angular.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/app.js"></script>
    <script src="~/js/MainController.js"></script>

    <script>
        // Add active class to the current button (highlight it)
        var header = document.getElementById("menu");
        var navbar = header.getElementsByClassName("nav-item");
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>